Cast nil to the generic type
Free Pascal 3.2.0 on Windows 10 64 bit requires you to cast this nil, otherwise you get:

`bare.types.pas(887,11) Error: (4001) Incompatible types: got "Pointer" expected "$gendef257"`